//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateCardCaptionLocalization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TemplateCardCaptionLocalization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausrichten Globalen.
        /// </summary>
        internal static string FieldTextAlignMode_AlignGlobal {
            get {
                return ResourceManager.GetString("FieldTextAlignMode_AlignGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatische Formattenkennung.
        /// </summary>
        internal static string FieldTextAlignMode_AutoSize {
            get {
                return ResourceManager.GetString("FieldTextAlignMode_AutoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerdefiniertes Format.
        /// </summary>
        internal static string FieldTextAlignMode_CustomSize {
            get {
                return ResourceManager.GetString("FieldTextAlignMode_CustomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template-Karte.
        /// </summary>
        internal static string LayoutViewDesignerHelper_DesigherControl_Root_Text {
            get {
                return ResourceManager.GetString("LayoutViewDesignerHelper_DesigherControl_Root_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boden.
        /// </summary>
        internal static string Locations_Bottom {
            get {
                return ResourceManager.GetString("Locations_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardmäßig.
        /// </summary>
        internal static string Locations_Default {
            get {
                return ResourceManager.GetString("Locations_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string Locations_Left {
            get {
                return ResourceManager.GetString("Locations_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reght.
        /// </summary>
        internal static string Locations_Right {
            get {
                return ResourceManager.GetString("Locations_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oben.
        /// </summary>
        internal static string Locations_Top {
            get {
                return ResourceManager.GetString("Locations_Top", resourceCulture);
            }
        }
    }
}
